### PR TITLE
first draft

### PR DESCRIPTION
**Pull request by nathanwilk7**
image

### CODE REVIEW

**Comment by nathanwilk7** [comment]
The "User Defined" glyph currently exists: 
image
The "User Defined" glyph is displayed for glyphs which do not currently exist. However, this "Engineered Region" glyph would be displayed for SO:0000804 per the vis spec. Would you like me to just leave out SO:0000804 so that it defaults to the "User Defined" glyph?

**Comment by nathanwilk7** [comment]
I can also modify the "User Defined" glyph if you'd like

**Comment by cjmyers** [comment]
User Defined Glyph is now the “[ ]” glyph.  Namely, if no glyph exists.  This glyph should ONLY be used by Engineered Region and its child SO terms.

Chris

**Comment by nathanwilk7** [comment]
So, are you saying you want the "User Defined" glyph to be updated to the "[ ]" symbol? And I'm not sure I understand your third sentence, can you clarify?

**Comment by cjmyers** [comment]
The BOX glyph used to be used for everything that did not have an already defined glyph (i.e., user defined meant no glyph assigned).  During the development of SBOLv2, we decided it should ONLY be used for Engineered Region SO term as well as its child terms:

http://www.sequenceontology.org/browser/current_svn/term/SO:0000804

Engineered Foreign Region, Engineered Foreign Region Gene, Engineered Gene, etc.

So, now anything that does not have a glyph assigned gets the "[ ]" glyph instead.

Is this clear?

**Comment by nathanwilk7** [comment]
I believe so, let me reiterate to you what I'm understanding I should do to m ake sure.
1. Set the BOX glyph to be displayed for engineered region and it's children
2. Change "User Defined" to use the "[ ]" glyph

**Comment by cjmyers** [comment]
Yep where user defined is the default case when no other glyph is available.

**Comment by nathanwilk7** [comment]
Great, will do

**Comment by nathanwilk7** [comment]
Ok, just updated this branch to have the same color as before and to show the BOX glyph for all engineered children as well. I'll work on "No Glyph Assigned" next

**Pull request merged**
