### PR TITLE
Merged interaction

### PR DESCRIPTION
**Pull request by asadeg02**
Addresses #99 #97 #85.
The purpose of this pull request was to remove the redundancy from interaction diagrams. 
With this new approach all the interaction happening on top of a circuit are merged together and are rendered in one diagram; if the nonDNA part participating in the interaction is degraded then degradation is not shown in a separate diagram either, other wise it has to be shown separately.
Also interactions are sorted so that inhibitions and stimulation are always rendered to the left of genetic productions.
below is a segment of VisBOL rendering for a SBOL file
final

For that SBOL, file these interactions are rendered separately. please note that since some of these proteins in that SBOL file don't participate in any other interaction with circuits, their degradation interactions has to be rendered separately, even though degradation interactions are merged into the circuit interactions.
rest

Merge interactions algorithm is in "lib/displayList.js" and it merges interactions using a segment id which has been given to the segments using componentDefinitions uri in "lib/getDisplayList.js".

### CODE REVIEW

**Comment by cjmyers** [comment]
This looks great.  I'm going to test this out now.

**Comment by cjmyers** [comment]
Looks like something is not checked in:

Error: Cannot find module './stimulatorArrow' from '/Users/myers/git/visbol-js/font/sbolv/interaction-arrows'
    at /Users/myers/git/synbiohub/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/Users/myers/git/synbiohub/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/myers/git/synbiohub/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/myers/git/synbiohub/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqCallback.oncomplete (fs.js:161:21)

**Comment by cjmyers** [comment]
Ah, I think I see the issue.  You likely moved simulatorArrow to stimulatorArrow, but then did not commit stimulatorArrow

**Comment by asadeg02** [comment]
Just Added it.

**Comment by cjmyers** [comment]
Looks great.  Merging.

**Pull request merged**
