### PR TITLE
Limit with omitted

### PR DESCRIPTION
**Pull request by dany-fu**
Issue #53 and #73 
Renders 30 glyphs max, the 31st glyph is the omitted glyph 

screen shot 2018-07-10 at 18 29 45

### CODE REVIEW

**Comment by cjmyers** [comment]
So, this actually will not work with SynBioHub.  SBH does not use browser.js, but goes directly to getDisplayList.  The addition of the omitted detail and the pruning of the extra segments should be done in getDisplayList.

**Comment by cjmyers** [comment]
This does not break anything, so it is fine to be merged, but I will leave this branch open, and a new pull request on this branch can be submitted later, which moves this functionality into getDisplayList.

**Comment by dany-fu** [comment]
Here, we are using the code that Zach had committed a while back for limiting, which is to slice the displayList. I closed the pull request after Arezoo raised the issue of how that could impact the interactions that she's currently working on, and it's also not an ideal long term solution if in the future we want to consider something like an expansion or some other way of rendering the rest of the glyphs. I think we should not limit the displayList but make the cut off during the rendering instead

**Comment by cjmyers** [comment]
Agreed.  I will revert this one.

**Pull request merged**
